### ISSUE TITLE
dependency on HISTORY.rst? 

### ISSUE THREAD

**Issue by yosun** [soumickmj/pytorch-complex#8]
```
  File "/home/yc/anaconda3/lib/python3.7/site-packages/kornia/core/_backend.py", line 24, in <module>
    complex = torch.complex
AttributeError: module 'torch' has no attribute 'complex'
(HRN) yc@razer3080ti:~/testing3dai/HRN/HRN$ pip install pytorch-complex
Keyring is skipped due to an exception: 'keyring.backends'
Collecting pytorch-complex
  Using cached pytorch-complex-0.1.1.tar.gz (39 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/yc/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qgsn91my/pytorch-complex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qgsn91my/pytorch-complex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-qgsn91my/pytorch-complex/pip-egg-info
         cwd: /tmp/pip-install-qgsn91my/pytorch-complex/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qgsn91my/pytorch-complex/setup.py", line 10, in <module>
        with open('HISTORY.rst', "r", encoding='utf8') as history_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by dev-sora** [comment]
Hi,

Did you try install the package directly from git source?
Clone this repository at any directory as you like and run `pip install ./pytorch-complex`
